### PR TITLE
Bump Microsoft.VisualStudio.Composition version

### LINKED ISSUE #10529: Plugin manager disappeared after update to 4.0.1
### Environment

- Git Extensions 4.0.1.15887
- Build f2567dea28bbf0e2cbcd2a95d4c7200e47d0d671
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.12
- DPI 96dpi (no scaling)
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 3.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 3.1.29 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 3.1.30 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

### Issue description

After update to 4.0.1 Plugin manager is no longer visible in Plugins menu. The Plugin manager is still present in `AppData\Local\GitExtensions\UserPlugins`. The Gerrit plugin that's in the same UserPlugins directory does still work.

### Steps to reproduce

Update to GitExtensions 4.0.1

### Did this work in previous version of GitExtensions?

Yes, 4.0.0.

### Diagnostics

_No response_

### PR DESCRIPTION
**Pull request by RussKie**
Microsoft.VisualStudio.Composition v16.9 depended on System.ComponentModel.Composition v4.5+; which led to us shipping v4.6.

The Plugin Manager 184 was built against [System.ComponentModel.Composition v6.0.0.](https://github.com/gitextensions/gitextensions.pluginmanager/blob/bbaafa6eda217877822d0993d1fbea57bc0239f1/src/GitExtensions.PluginManager/GitExtensions.PluginManager.csproj#L21) As a result, it would fail to load because the dependency was not satisfied.

* Add an explicit dependency on System.ComponentModel.Composition v6.0.
* Bump Microsoft.VisualStudio.Composition to v17.2, as it now depends on System.ComponentModel.Composition v6.0+.

Resolves #10529

### CODE REVIEW

**Review by mstv — COMMENTED** [review]
Building a release, I get many warnings like
"GitCommands\Git\BatchProgressEventArgs.cs(15,58): error SA1629: Documentation text should end with a period"

**Comment by RussKie** [comment]
> Building a release, I get many warnings like
> "GitCommands\Git\BatchProgressEventArgs.cs(15,58): error SA1629: Documentation text should end with a period"

I don't... `git clean -xdf`?
image

**Comment by RussKie** [comment]
Having installed the built msi I can see the correct version of the PM loaded as well as the correct version of S.CM.C:
image

However, I still don't see it in the menu....

**Review by mstv — APPROVED** [review]
Yes, it works now.
I had already run `git clean -xdf`. I did not `build` but `publish`, which usually suffices.

The portable build works, it starts PluginManager 2.0.0.184.

**Comment by RussKie** [comment]
The PM isn't still being recognised:
image

**Comment by RussKie** [comment]
@maraf this doesn't look right:
image

**Comment by RussKie** [comment]
I rebuilt the PM locally targeting v4.0.1 release, and it appears to work as expected:
image

**Comment by mstv** [comment]
Installed on a Win10 VM without GE installed before.

image

- Git Extensions 33.33.33
- Build 13ddc3dac86c7f8c5d27af4edbf6b5110f873451
- Git 2.31.1.windows.1 (recommended: 2.38.1 or later)
- Microsoft Windows NT 10.0.16299.0
- .NET 6.0.12
- DPI 96dpi (no scaling)
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by RussKie** [comment]
That's a good find, @mstv. Can you try adding a PackageManager.UI.runtimeconfig.json manually for a test?
```json
{
  "runtimeOptions": {
    "tfm": "net6.0",
    "frameworks": [
      {
        "name": "Microsoft.NETCore.App",
        "version": "6.0.0"
      },
      {
        "name": "Microsoft.WindowsDesktop.App",
        "version": "6.0.0"
      }
    ],
    "configProperties": {
      "System.Reflection.Metadata.MetadataUpdater.IsSupported": false
    }
  }
}
```

**Comment by RussKie** [comment]
I confirmed the fix locally by installing https://ci.appveyor.com/api/buildjobs/n5i8ljiegavmupt5/artifacts/GitExtensions-4.0.2.15942-c6270e961.msi. Before running the app, I removed `C:\Program Files\dotnet` and `C:\Program Files (x86)\dotnet` folders too.
